
spring:
 application:
  name: emminence-project
 datasource:
   url: 'jdbc:mysql://localhost:3306/testdb'
   driverClassName: 'com.mysql.cj.jdbc.Driver'
   username: 'root'
   password: 'root'
 jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.MySQLDialect
   hibernate:
    ddl-auto: update
 data:
    jpa:
      repositories:
        enabled: true

securityKey: YVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9DYVCQG8mxNrNBxhezVbY229ywJN060R9D
jwtExpTime: 3600000


server: 
 port: 8091
 
 

